/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ArchiveHistorySummaryItem } from './archiveHistorySummaryItem';

export type ArchiveResponseHistorySummaries = ArchiveHistorySummaryItem[] | null;
