/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ArchiveResponseFileSummaries } from './archiveResponseFileSummaries';
import type { ArchiveResponseHistorySummaries } from './archiveResponseHistorySummaries';

export interface ArchiveResponse {
  date: string;
  file_summaries?: ArchiveResponseFileSummaries;
  history_summaries?: ArchiveResponseHistorySummaries;
}
