/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { WebhooksInfo } from './webhooksInfo';

export interface CreateAccountResponse {
  message: string;
  user_id: number;
  email: string;
  webhooks: WebhooksInfo;
}
