/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EpsonCreateDestinationRequestBaseUrl } from './epsonCreateDestinationRequestBaseUrl';
import type { EpsonCreateDestinationRequestAuthUrl } from './epsonCreateDestinationRequestAuthUrl';
import type { EpsonCreateDestinationRequestApiKey } from './epsonCreateDestinationRequestApiKey';
import type { EpsonCreateDestinationRequestRefreshToken } from './epsonCreateDestinationRequestRefreshToken';
import type { EpsonCreateDestinationRequestClientId } from './epsonCreateDestinationRequestClientId';
import type { EpsonCreateDestinationRequestClientSecret } from './epsonCreateDestinationRequestClientSecret';

export interface EpsonCreateDestinationRequest {
  password: string;
  use_dummy?: boolean;
  base_url?: EpsonCreateDestinationRequestBaseUrl;
  auth_url?: EpsonCreateDestinationRequestAuthUrl;
  api_key?: EpsonCreateDestinationRequestApiKey;
  refresh_token?: EpsonCreateDestinationRequestRefreshToken;
  client_id?: EpsonCreateDestinationRequestClientId;
  client_secret?: EpsonCreateDestinationRequestClientSecret;
  alias_name?: string;
  user_id: number;
  destination_base_url: string;
}
