/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EpsonPrintFromMarkdownRequestBaseUrl } from './epsonPrintFromMarkdownRequestBaseUrl';
import type { EpsonPrintFromMarkdownRequestAuthUrl } from './epsonPrintFromMarkdownRequestAuthUrl';
import type { EpsonPrintFromMarkdownRequestApiKey } from './epsonPrintFromMarkdownRequestApiKey';
import type { EpsonPrintFromMarkdownRequestRefreshToken } from './epsonPrintFromMarkdownRequestRefreshToken';
import type { EpsonPrintFromMarkdownRequestClientId } from './epsonPrintFromMarkdownRequestClientId';
import type { EpsonPrintFromMarkdownRequestClientSecret } from './epsonPrintFromMarkdownRequestClientSecret';
import type { EpsonPrintFromMarkdownRequestPrintSettings } from './epsonPrintFromMarkdownRequestPrintSettings';

export interface EpsonPrintFromMarkdownRequest {
  password: string;
  use_dummy?: boolean;
  base_url?: EpsonPrintFromMarkdownRequestBaseUrl;
  auth_url?: EpsonPrintFromMarkdownRequestAuthUrl;
  api_key?: EpsonPrintFromMarkdownRequestApiKey;
  refresh_token?: EpsonPrintFromMarkdownRequestRefreshToken;
  client_id?: EpsonPrintFromMarkdownRequestClientId;
  client_secret?: EpsonPrintFromMarkdownRequestClientSecret;
  job_name?: string;
  md: string;
  filename?: string;
  print_settings?: EpsonPrintFromMarkdownRequestPrintSettings;
}
