/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EpsonCapabilityRequestBaseUrl } from './epsonCapabilityRequestBaseUrl';
import type { EpsonCapabilityRequestAuthUrl } from './epsonCapabilityRequestAuthUrl';
import type { EpsonCapabilityRequestApiKey } from './epsonCapabilityRequestApiKey';
import type { EpsonCapabilityRequestRefreshToken } from './epsonCapabilityRequestRefreshToken';
import type { EpsonCapabilityRequestClientId } from './epsonCapabilityRequestClientId';
import type { EpsonCapabilityRequestClientSecret } from './epsonCapabilityRequestClientSecret';

export interface EpsonCapabilityRequest {
  password: string;
  use_dummy?: boolean;
  base_url?: EpsonCapabilityRequestBaseUrl;
  auth_url?: EpsonCapabilityRequestAuthUrl;
  api_key?: EpsonCapabilityRequestApiKey;
  refresh_token?: EpsonCapabilityRequestRefreshToken;
  client_id?: EpsonCapabilityRequestClientId;
  client_secret?: EpsonCapabilityRequestClientSecret;
}
