/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface FileWebhookLogItem {
  id: number;
  external_id: string;
  created_at: string;
}
