/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { FileBinaryResponseContentType } from './fileBinaryResponseContentType';
import type { FileBinaryResponseCreatedAt } from './fileBinaryResponseCreatedAt';

export interface FileBinaryResponse {
  file_id: number;
  filename: string;
  content_base64: string;
  content_type?: FileBinaryResponseContentType;
  created_at?: FileBinaryResponseCreatedAt;
}
