/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryItemUrl } from './historyItemUrl';
import type { HistoryItemTitle } from './historyItemTitle';
import type { HistoryItemDescription } from './historyItemDescription';
import type { HistoryItemCreatedAt } from './historyItemCreatedAt';

export interface HistoryItem {
  id: number;
  url?: HistoryItemUrl;
  title?: HistoryItemTitle;
  description?: HistoryItemDescription;
  created_at?: HistoryItemCreatedAt;
}
