/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryPayloadUrl } from './historyPayloadUrl';
import type { HistoryPayloadTitle } from './historyPayloadTitle';
import type { HistoryPayloadDescription } from './historyPayloadDescription';
import type { HistoryPayloadTimestamp } from './historyPayloadTimestamp';
import type { HistoryPayloadExternalId } from './historyPayloadExternalId';

export interface HistoryPayload {
  url?: HistoryPayloadUrl;
  title?: HistoryPayloadTitle;
  description?: HistoryPayloadDescription;
  timestamp?: HistoryPayloadTimestamp;
  external_id?: HistoryPayloadExternalId;
}
