/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TestEndpointResponseDate } from './testEndpointResponseDate';

export interface TestEndpointResponse {
  test: string;
  date?: TestEndpointResponseDate;
  tags: string[];
}
