/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TokenResponseRefreshToken } from './tokenResponseRefreshToken';

export interface TokenResponse {
  access_token: string;
  token_type: string;
  refresh_token?: TokenResponseRefreshToken;
}
