/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserProfileActivityFileActiveDates } from './userProfileActivityFileActiveDates';
import type { UserProfileActivityHistoryActiveDates } from './userProfileActivityHistoryActiveDates';

export interface UserProfileActivity {
  id: number;
  email: string;
  month: string;
  active_dates: number[];
  file_active_dates?: UserProfileActivityFileActiveDates;
  history_active_dates?: UserProfileActivityHistoryActiveDates;
}
